#!/usr/bin/env python3
"""Generate firefighter.srdf, including the collision matrix.

The disable_collisions entries are not hand-written. Every link pair is
classified by sampling 1200 random arm configurations and testing whether the
links' axis-aligned bounding boxes ever overlap:

  Adjacent  - connected by a joint
  Never     - AABBs never overlapped in any sample. AABB overlap is a superset
              of real mesh collision, so "never overlapped" proves the pair can
              never collide. Disabling is safe.
  Default   - overlapped in every sample (the gripper four-bar, which the URDF
              models as an open chain, so the links interpenetrate by design)

Pairs that overlap only sometimes are left ENABLED - those are the real
collision checks, including arm-vs-frame and arm-vs-holder.

Run:  python3 gen_srdf.py
"""
import itertools
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
OUT = os.path.join(PKG, "config", "firefighter.srdf")

DESC = "/home/samuel/colcon_ws/install/pdms_gripper_description/share/pdms_gripper_description"
MYCOBOT = "/home/samuel/colcon_ws/src/mycobot_ros2/mycobot_description"
URDF = os.path.join(DESC, "urdf", "mycobot_320_pi_2022_workcell.urdf")

ARM = ["joint2_to_joint1", "joint3_to_joint2", "joint4_to_joint3",
       "joint5_to_joint4", "joint6_to_joint5", "joint6output_to_joint6"]

# The adaptive gripper is a closed four-bar, but URDF can only express an open
# chain, so its links interpenetrate by design as the fingers travel. Every
# pair inside the gripper must be disabled or planning fails the moment the
# gripper opens (gripper_left3 vs gripper_left2 was the observed failure).
GRIPPER_LINKS = ["gripper_base", "gripper_left1", "gripper_left2", "gripper_left3",
                 "gripper_right1", "gripper_right2", "gripper_right3"]
N_SAMPLES = 1200


def load_renderer():
    for p in (os.path.join(DESC, "tools"), os.path.join(PKG, "..", "pdms_gripper_description", "tools")):
        if os.path.exists(os.path.join(p, "render_urdf.py")):
            sys.path.insert(0, p)
            break
    import render_urdf as R
    R.resolve = lambda u: (lambda pkg, rel: os.path.join(
        DESC if pkg == "pdms_gripper_description" else MYCOBOT, rel))(
            *u.replace("package://", "").split("/", 1))
    return R


def classify(R):
    links, joints = R.load_urdf(URDF)
    names = [n for n, (uri, _) in links.items() if uri]
    np.random.seed(0)
    cloud = {}
    for n in names:
        uri, Tv = links[n]
        V, _ = R.load_dae(R.resolve(uri))
        if len(V) > 400:
            V = V[np.random.choice(len(V), 400, replace=False)]
        cloud[n] = (Tv[:3, :3] @ V.T).T + Tv[:3, 3]

    adj = {frozenset((j["parent"], j["child"])) for j in joints}
    pairs = [frozenset(p) for p in itertools.combinations(sorted(names), 2)]
    hits = {p: 0 for p in pairs}
    for _ in range(N_SAMPLES):
        q = {j: np.random.uniform(-2.6, 2.6) for j in ARM}
        q["gripper_controller"] = np.random.uniform(-1.0, 0.2)
        pose = R.fk(links, joints, q)
        box = {}
        for n in names:
            if n not in pose:
                continue
            T = pose[n]
            W = (T[:3, :3] @ cloud[n].T).T + T[:3, 3]
            box[n] = (W.min(0), W.max(0))
        for p in pairs:
            a, b = tuple(p)
            if a in box and b in box:
                (a0, a1), (b0, b1) = box[a], box[b]
                if np.all(a1 >= b0) and np.all(a0 <= b1):
                    hits[p] += 1

    rows, kept = [], 0
    for p in sorted(pairs, key=lambda s: sorted(tuple(s))):
        a, b = sorted(tuple(p))
        c = hits[p]
        if a in GRIPPER_LINKS and b in GRIPPER_LINKS:
            rows.append((a, b, "Default"))   # four-bar closure, see note above
        elif p in adj:
            rows.append((a, b, "Adjacent"))
        elif c == 0:
            rows.append((a, b, "Never"))
        elif c == N_SAMPLES:
            rows.append((a, b, "Default"))
        else:
            kept += 1
    return rows, kept


SRDF_HEAD = '''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/gen_srdf.py - do not hand-edit the collision matrix. -->
<robot name="firefighter">
    <group name="arm_group">
        <chain base_link="base" tip_link="gripper_base"/>
    </group>

    <group name="gripper">
        <joint name="gripper_controller"/>
    </group>

    <end_effector name="fork_gripper" parent_link="gripper_base"
                  group="gripper" parent_group="arm_group"/>

    <group_state name="home" group="arm_group">
        <joint name="joint2_to_joint1" value="0"/>
        <joint name="joint3_to_joint2" value="-0.6"/>
        <joint name="joint4_to_joint3" value="1.2"/>
        <joint name="joint5_to_joint4" value="-0.6"/>
        <joint name="joint6_to_joint5" value="0"/>
        <joint name="joint6output_to_joint6" value="0"/>
    </group_state>

    <group_state name="zero" group="arm_group">
        <joint name="joint2_to_joint1" value="0"/>
        <joint name="joint3_to_joint2" value="0"/>
        <joint name="joint4_to_joint3" value="0"/>
        <joint name="joint5_to_joint4" value="0"/>
        <joint name="joint6_to_joint5" value="0"/>
        <joint name="joint6output_to_joint6" value="0"/>
    </group_state>

    <group_state name="open" group="gripper">
        <joint name="gripper_controller" value="0"/>
    </group_state>

    <group_state name="closed" group="gripper">
        <joint name="gripper_controller" value="-0.55"/>
    </group_state>

'''


def main():
    R = load_renderer()
    rows, kept = classify(R)
    with open(OUT, "w") as f:
        f.write(SRDF_HEAD)
        f.write("    <!-- %d pairs disabled; %d pairs left enabled for real "
                "collision checking (arm vs frame/holder included) -->\n" % (len(rows), kept))
        for a, b, why in rows:
            f.write('    <disable_collisions link1="%s" link2="%s" reason="%s"/>\n' % (a, b, why))
        f.write("</robot>\n")
    print("wrote", OUT)
    from collections import Counter
    print("  ", dict(Counter(w for _, _, w in rows)), " enabled pairs:", kept)


if __name__ == "__main__":
    main()
